### ISSUE TITLE
open-cd support

### ISSUE THREAD

**Issue by likyoo** [tangkai-RS/ChangeAnywhere#3]
Hi~ Kai,  thanks for your excellent work! We are planning to support ChangeAnywhere pre-trained models in open-cd. 
Looking forward to cooperating with you~ 😃

**Comment by tangkai-RS** [comment]
Thanks to open-cd for facilitating ChangeAnywhere development! I'm willing to offer any support I can. 😃

**Comment by tangkai-RS** [comment]
BTW, we recently trained the pre-training weights of WHU-CD and LEVIR-CD with amazing results (i.e., zero-shot), which will be uploaded to GitHub recently.

**Comment by likyoo** [comment]
That's great! If possible, we can contact on WeChat (likyoo7).
