### ISSUE TITLE
about zero-shot experiment on the SCD task

### ISSUE THREAD

**Issue by haoranwu22** [tangkai-RS/ChangeAnywhere#4]
The categories of the data generated in the paper are not consistent with the SECOND dataset, how to proceed to train the network with the generated data and conduct zero-shotexperiments on the SECOND dataset.

**Comment by tangkai-RS** [comment]
手稿中目前仅使用SECOND数据集的进行二元变化检测实验，并没有使用其语义标签，因此不涉及语义类别不匹配问题

**Comment by haoranwu22** [comment]
我还有个问题，Change Events Simulation（由一个时刻生成下一时刻的语义mask）这部分有可参考的实现方式或者参考文献吗？这对我十分重要，谢谢！

**Comment by tangkai-RS** [comment]
目前没有参考文献，具体是基于open cv实现的，所有代码会在之后开源。如果您的工作迫切需要改代码，可以加v进一步交流 tk1362723810
